addSbtPlugin("org.typelevel"    % "sbt-tpolecat"  % "0.5.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.5.2")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"  % "0.14.3")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"   % "0.6.4")
addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "2.1.0")
